### PR TITLE
Feature/user

### PR DESCRIPTION
**Pull request by Morrism1**
# Private-Events

> In this project, we created the:

* Added validations, 

* Generated migrations

* Created associations between models, and 

* Added user authentication using Devise.

* Styled the site  using Materialize CSS

* Wrote unit and integration tests using RSpec and Capybara

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- While running migrations I get the following error: `PG::UndefinedTable: ERROR:  table "users" does not exist`. Here is the full stack trace:

  image

  As you can see, the `drop users` migration ran first. Then all the other migrations were canceled. This is because you are dropping the users table first and then trying to migrate other tables that depend on the users table. Since you are creating the users table only once (and you should), you don't need to drop it first. Please remove that migration.

- Please remove all logic from views. There should be absolutely no logic in views. Instead, outsource your view logic to helpers. There is currently logic in these files:
  * `users/index`
  * `shared/_nav`
  * `events/show`

- When you are writing tests, remember to write tests for both positive and negative scenarios.
  * In `spec/models/events_spec`, you are testing for negative scenarios. Please add tests for positive scenarios as well.
  * For the request specs, add tests for negative scenarios.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by Morrism1** [comment]
> # Changes required 🛑
> ## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!
> ### But in order to get it approved, we need to work on some changes. Let's see...
> * While running migrations I get the following error: `PG::UndefinedTable: ERROR:  table "users" does not exist`. Here is the full stack trace:
>   image
>   As you can see, the `drop users` migration ran first. Then all the other migrations were canceled. This is because you are dropping the users table first and then trying to migrate other tables that depend on the users table. Since you are creating the users table only once (and you should), you don't need to drop it first. Please remove that migration.
> * Please remove all logic from views. There should be absolutely no logic in views. Instead, outsource your view logic to helpers. There is currently logic in these files:
>   
>   * `users/index`
>   * `shared/_nav`
>   * `events/show`
> * When you are writing tests, remember to write tests for both positive and negative scenarios.
>   
>   * In `spec/models/events_spec`, you are testing for negative scenarios. Please add tests for positive scenarios as well.
>   * For the request specs, add tests for negative scenarios.
> 
> Your project looks absolutely fantastic. Just make these changes and apply for another code review.
> 
> Happy coding 👨‍💻
> 
> _Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)_
> 
> **Tirthajyoti Ghosh**
> 
> [GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

Drop user error, you had was due to I dropped devise user table and created my own
To avoid the issue next it is advised to use rails **db:schema:load** instead of rails db:migration

**Comment by Morrism1** [comment]
> # Changes required 🛑
> ## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!
> ### But in order to get it approved, we need to work on some changes. Let's see...
> * While running migrations I get the following error: `PG::UndefinedTable: ERROR:  table "users" does not exist`. Here is the full stack trace:
>   image
>   As you can see, the `drop users` migration ran first. Then all the other migrations were canceled. This is because you are dropping the users table first and then trying to migrate other tables that depend on the users table. Since you are creating the users table only once (and you should), you don't need to drop it first. Please remove that migration.
> * Please remove all logic from views. There should be absolutely no logic in views. Instead, outsource your view logic to helpers. There is currently logic in these files:
>   
>   * `users/index`
>   * `shared/_nav`
>   * `events/show`
> * When you are writing tests, remember to write tests for both positive and negative scenarios.
>   
>   * In `spec/models/events_spec`, you are testing for negative scenarios. Please add tests for positive scenarios as well.
>   * For the request specs, add tests for negative scenarios.
> 
> Your project looks absolutely fantastic. Just make these changes and apply for another code review.
> 
> Happy coding 👨‍💻
> 
> _Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)_
> 
> **Tirthajyoti Ghosh**
> 
> [GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

The logic in the **shared/_nav** is there for a purpose and will not be changed. I used Materialize CSS responsive navbar for desktop and mobile the If statement you see they are there because of are repeated due to differences in classes. Sorry about that.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
